Game.cpp
Map.cpp
Map.h
Overflow Software Design Game.vcxproj
Overflow Software Design Game.vcxproj.filters
Player.cpp
Player.h
Tile.cpp
Tile.h
UserInputValidation.cpp
UserInputValidation.h
UserInterface.cpp
UserInterface.h

Created architecture for Overflow Game
Created Player, Tile, Map, UserInputValidation, UserInterface .h and .cpp files respectively.
Edited .h and .cpp files above and added methods/constructors as part of the architecture

Overflow 26 display intro message backstory and rules

---

Chunk.cpp
Chunk.h
ConsoleColors.cpp
ConsoleColors.h
Game.cpp
Overflow Software Design Game.vcxproj
Tile.cpp
Tile.h

Added color compatibility and a chunk display for a single dummy chunk.
Redesigned the tile class; please make sure to choose the new changes.

OVERFLOW-31

---

Game.cpp
UserInputValidation.cpp
UserInputValidation.h

Updated UserInputValidation.h and .cpp
Added MoveChecker in both

Overflow 32 explore the starting area

---

Chunk.cpp
Chunk.h
Game.cpp
Map.cpp
Map.h
Overflow Software Design Game.vcxproj
Player.cpp
Player.h
Tester.cpp
Tile.cpp
Tile.h

Finished adding player movement and threw together a simple version of what the game could look like in the Game.cpp file.

Overflow 27 player movement between starting area and city

---

Game.cpp
Player.cpp
Player.h
UserInputValidation.cpp
UserInputValidation.h

Sprint1 game implementation

---

Game.cpp
UserInterface.cpp

New Branch to merge into main: edited UserInterface.cpp and Game.cpp to include game rules and game backstory

The correct backstory and rules

---

Chunk.cpp
Chunk.h
ConsoleColors.h
Game.cpp
Map.cpp
Map.h
Player.cpp
Player.h

Added map compatibility and display mechanics.

Pull Request for OVERFLOW-31 into main

---

Chunk.cpp
Chunk.h
ConsoleColors.h
Game.cpp
Map.cpp
Map.h

added ability to display player and show updates to its movement

pretty moving colors

---

Entity.cpp
Quest.h

Quest.h class had two objects with the same name
Entity.cpp class was missing constructor definitions

Fixed bug where game was not compiling correctly:

---

Game.cpp
UserInputValidation.cpp
UserInputValidation.h

Main edits are in the Game.cpp, UserInputValidation.cpp/h files. 
My tests with it ran fine and all worked as I intended.

Overflow 56 validating input for the map command

---

UserInputValidation.cpp
UserInputValidation.h

Deleted the ProcessAction method as GameManager should be the one processes the player actions
ActionChecker will return true if an action (MAP, PICKUP, INSPECT) is entered, and will return false if they are not.
CheckValidAction now includes PICKUP and INSPECT enums in the cases of switch statement.
UserInputValidation class does now "#Include "Player.h" -- this can be refactored later as it is currently not in use

OVERFLOW-64

---

Game.cpp
GameManager.cpp
GameManager.h
Tile.cpp
Tile.h
UserInputValidation.cpp
UserInputValidation.h

Updated Game.cpp to include an example of how items can be generated and set. Also cleaned up how it displays map and changed method calls to use pointer de-referencing for new Item pointer in Tile class.
Added a GetPlayerLocationTile() method to Gamemanager class because the method call needed to get Player's current Tile was too long to use every time in the Game.cpp file.
The Item object in the Tile class has been changed to a pointer. The setters and getters have been adjusted to reflect that.
Minor changes in UserInputValidation to remove circular dependency from including Player.h and adjusted ActionChecker() method because it was reassigning one of its parameters and using it as a local variable.

OVERFLOW-28 Final Commit Before Testing

---

Game.cpp

Fixed bug causing PICKUP and INSPECT commands to crash game. Branch is now ready to merge.

Overflow 28 display items that are found by the player in the starting area

---

Game.cpp
Inventory.cpp
Inventory.h
UserInputValidation.cpp

Created the inventory. Able to display it when prompted. Adds picked up items to inventory.

Overflow 39 create and display the inventory of the player

---

Enemy.cpp
Enemy.h
Game.cpp
GameManager.cpp
Tile.cpp
Tile.h

Added enemy implementation and updated map display so that text appeared below map when it is displayed.

Overflow 40 player can encounter the first enemy dust golem

---

Enemy.cpp
Enemy.h
Game.cpp
GameManager.cpp
GameManager.h
Player.cpp
Player.h
Tile.cpp
UserInputValidation.cpp
UserInputValidation.h

Pull request to merge combat system implementation to main.
Combat system has full implementation except for when player health reaches 0. That will be fixed as part of Jira story at a later date.

Overflow 46 combat system tutorial for the player

---

Game.cpp
GameManager.cpp
GameManager.h
UserInputValidation.cpp
UserInputValidation.h

Pull request for Hero's Quest Puzzle branch.
Changes already tested so merging right away to get test build ready for cross team testing.

Overflow 85 implementing the end of the forest puzzle

---

Chunk.cpp
Chunk.h
Enemy.cpp
Enemy.h
Game.cpp
GameManager.cpp
GameManager.h
Tile.cpp

After researching C++ pointers, the only way to fix dangling pointers is to update them all manually so I added that functionality for the muli-tile enemies. When they are defeted, all pointers to them in the Chunk will be set to nullptr.

Enemy Icon Display Fixed

---

Game.cpp
GameManager.cpp
Player.cpp
UserInputValidation.cpp
UserInterface.cpp

Missing UI fix

---

Enemy.cpp
Enemy.h
Game.cpp
GameManager.cpp
Player.cpp

Updated Enemy class to include a description for created enemies-- updated contructor to include this
Game.cpp now gives a decription of the enemy to the player before a battle is begun.
GameManager method GameBattleManager now includes a check to see if the player is in the first battle with the dust golem-- if yes, it prints out the prompt for the tutorial battle
Player default damage updated to be 2, so that deflection can be showcased to work. it was 1 before which caused some issues with the way deflection works
There is now a prompt that introduces the player to the battle system and what the actions do.
Later implementations can block all enemies from spawning in until the first enemy has been defeated.

OVERFLOW-46

---

Game.cpp
GameManager.cpp
GameManager.h

Puzzle is located on Chunk (3, 1) and Tile (2, 6) and can not be started until the player has completed the tutorial battle.

Added River Obsticle Puzzle titled Three Stones Puzzle.

---

Enemy.cpp
Enemy.h
Game.cpp
GameManager.cpp
GameManager.h

Implemented enemies in proper areas of the map. It has been Tested by Drilon and said to have worked
I commented out the initialization of enemies on Game.cpp and made a new method in GameManager called SpawnStartingAreaEnemies

Overflow 119 implement different instances of the starting area enemies mushroom warrior and wizard squirrel

---

GameManager.cpp

Added implementation of a full heal when the player defeats the Dust Golem.
Note: This will trigger again if another Dust Golem is placed on the map.

Overflow 118 heal the player to full health once they have beaten the dust golem in the starting area

---

Game.cpp
GameManager.cpp
GameManager.h
Inventory.cpp
Inventory.h
Player.cpp
Player.h
UserInputValidation.cpp
UserInputValidation.h
UserInterface.cpp

Added item usage implementation.

Overflow 127 implement item usage

---

Game.cpp
GameManager.h

Implemented the spellbook thief
Not a traditional NPC as text just appears once you enter Sprintville
Removes the player's spellbook they got from the original quest

Overflow 117 implement spellbook thief npc

---

Game.cpp
GameManager.cpp
GameManager.h

Implemented the ship captain NPC 
He sits at the ship and gives you back ur spellbook
you have to talk to this NPC to get the spellbook bacl

Overflow 143 implementing ship captain npc

---

Game.cpp
GameManager.cpp
GameManager.h
Inventory.cpp
Inventory.h
Item.cpp
Item.h
Player.cpp
Player.h
UserInputValidation.cpp
UserInputValidation.h
UserInterface.cpp

Added equipment functionality. The player can now equip items marked as equipment and weapons.
The player has 3 equipment slots.
Hats: Used to increase the player's max HP.
Robes: Used to increase the player's evasiveness.
Weapons: Used to increase the player's damage.
The player can equip these items by typing "EQUIP" as an action.

Overflow 128 implementing different weapon equipment into the game

---

Game.cpp
GameManager.cpp
GameManager.h

Designing and Implementing Lord Vallonious (final boss)

Overflow 120 design and implement lord vallonious
